export const organisations = [
  { id: '1', org_pipedrive_id: '100', name: 'Chobham Wealth Management', address: 'Surrey, UK', company_status: 'LLP', website: '', vendor_ownership_structure: 'John Fahy', authorisation_status: 'FCA Authorised', fca_number: '123456', id_urn: 'URN001', date_created: '2020-01-15' },
  { id: '2', org_pipedrive_id: '101', name: 'Goodman Financial Planning', address: 'London, UK', company_status: 'Ltd', website: '', vendor_ownership_structure: 'Peter Goodman', authorisation_status: 'FCA Authorised', fca_number: '234567', id_urn: 'URN002', date_created: '2019-03-20' },
  { id: '3', org_pipedrive_id: '102', name: 'Strategic Financial Portfolios', address: 'Birmingham, UK', company_status: 'Ltd', website: '', vendor_ownership_structure: 'Mohammed Bostan', authorisation_status: 'FCA Authorised', fca_number: '345678', id_urn: 'URN003', date_created: '2021-06-10' },
  { id: '4', org_pipedrive_id: '103', name: 'Atkinson White Ltd', address: 'Manchester, UK', company_status: 'Ltd', website: '', vendor_ownership_structure: 'Neil White', authorisation_status: 'FCA Authorised', fca_number: '456789', id_urn: 'URN004', date_created: '2018-11-05' },
  { id: '5', org_pipedrive_id: '104', name: 'Evolve Financial Management', address: 'Bristol, UK', company_status: 'Ltd', website: 'https://evolvefm.net', vendor_ownership_structure: 'Mike Fisher', authorisation_status: 'FCA Authorised', fca_number: '567890', id_urn: 'URN005', date_created: '2020-07-22' },
  { id: '6', org_pipedrive_id: '105', name: 'Bowman Financial Planning Limited', address: 'Leeds, UK', company_status: 'Ltd', website: '', vendor_ownership_structure: 'Paul Catling', authorisation_status: 'FCA Authorised', fca_number: '678901', id_urn: 'URN006', date_created: '2022-02-14' },
  { id: '7', org_pipedrive_id: '106', name: 'Avon Financial Advisers Ltd', address: 'Bath, UK', company_status: 'Ltd', website: '', vendor_ownership_structure: 'Stephen Cook', authorisation_status: 'FCA Authorised', fca_number: '789012', id_urn: 'URN007', date_created: '2019-09-30' },
  { id: '8', org_pipedrive_id: '107', name: 'Jones Hill Ltd', address: 'Oxford, UK', company_status: 'Ltd', website: '', vendor_ownership_structure: 'Brian Hill', authorisation_status: 'FCA Authorised', fca_number: '890123', id_urn: 'URN008', date_created: '2020-04-18' },
  { id: '9', org_pipedrive_id: '108', name: 'Ian J Hunt & Associates', address: 'Cambridge, UK', company_status: 'Partnership', website: '', vendor_ownership_structure: 'Ian John Hunt', authorisation_status: 'FCA Authorised', fca_number: '901234', id_urn: 'URN009', date_created: '2021-12-01' },
  { id: '10', org_pipedrive_id: '109', name: 'Prolific Financial Services Limited', address: 'Edinburgh, UK', company_status: 'Ltd', website: '', vendor_ownership_structure: 'Simon Allan', authorisation_status: 'FCA Authorised', fca_number: '012345', id_urn: 'URN010', date_created: '2019-05-25' },
]

export const contacts = [
  { id: '1', contact_pipedrive_id: '4487', name: 'John Fahy', email: 'john@chobhamwm.co.uk', phone: '07700 900001', age: '52', job_title: 'Principal', date_created: '2020-01-15', organisation_id: '1' },
  { id: '2', contact_pipedrive_id: '4488', name: 'Peter Goodman', email: 'peter@goodmanfp.co.uk', phone: '', age: '', job_title: 'Director', date_created: '2019-03-20', organisation_id: '2' },
  { id: '3', contact_pipedrive_id: '8630', name: 'Mohammed Bostan', email: 'mb@sfpwealth.co.uk', phone: '07855 526496', age: '', job_title: 'Managing Director', date_created: '2024-08-08', organisation_id: '3' },
  { id: '4', contact_pipedrive_id: '4490', name: 'Neil White', email: 'neil@atkinsonwhite.co.uk', phone: '07770 994500', age: '48', job_title: 'Director', date_created: '2018-11-05', organisation_id: '4' },
  { id: '5', contact_pipedrive_id: '4491', name: 'Mike Fisher', email: 'mike@evolvefm.net', phone: '01732 252130', age: '45', job_title: 'Managing Director', date_created: '2020-07-22', organisation_id: '5' },
  { id: '6', contact_pipedrive_id: '4492', name: 'Paul Catling', email: 'paul@bfpltd.co.uk', phone: '07899 664992', age: '55', job_title: 'Director', date_created: '2022-02-14', organisation_id: '6' },
  { id: '7', contact_pipedrive_id: '4493', name: 'Stephen Cook', email: 'stephen@avonfinancial.co.uk', phone: '07801 591127', age: '50', job_title: 'Principal', date_created: '2019-09-30', organisation_id: '7' },
  { id: '8', contact_pipedrive_id: '4494', name: 'Brian Hill', email: 'brian@joneshill.co.uk', phone: '07711 428941', age: '58', job_title: 'Director', date_created: '2020-04-18', organisation_id: '8' },
  { id: '9', contact_pipedrive_id: '4495', name: 'Ian John Hunt', email: 'ian@ijhcfp.co.uk', phone: '07976 604797', age: '61', job_title: 'Principal', date_created: '2021-12-01', organisation_id: '9' },
  { id: '10', contact_pipedrive_id: '4496', name: 'Simon Allan', email: 'simon.allan@prolific-ifa.co.uk', phone: '07815 053470', age: '44', job_title: 'Managing Director', date_created: '2019-05-25', organisation_id: '10' },
  { id: '11', contact_pipedrive_id: '4497', name: 'Justin Riley', email: 'justin@zestfc.co.uk', phone: '07722 100200', age: '42', job_title: 'Director', date_created: '2021-03-15', organisation_id: '2' },
  { id: '12', contact_pipedrive_id: '4498', name: 'Joe Hill', email: 'joe@ilpg.co.uk', phone: '07711 428941', age: '39', job_title: 'Adviser', date_created: '2022-05-10', organisation_id: '8' },
]

export const deals = [
  { id: '1', deal_pipedrive_id: '4487', title: 'Chobham Wealth Management', value: '£198,000', weighted_value: '£99,000', currency: 'GBP', stage: 'Declined', status: 'open', owner: 'Sam Smith', contact_id: '1', organisation_id: '1', date_created: '2023-01-10', introductory_company: 'Chapters Capital', deal_size: 'Small (<£300k EBITDA)', deal_source: 'M&A Broker', reason_for_decline: 'Price disagreement', reason_for_decline_detail: '', basis_of_deal: 'Asset Purchase', fdd_lead: '', rdd_lead: '', latest_status_acquisition_committee: '', acquisition_type: 'Full Acquisition', deal_structure: 'Cash', headline_consideration: '£198,000', ri_multiple: '3.2x', net_turnover_multiple: '1.5x', ebitda_multiple: '4.1x', assets_under_advice: '£60m', number_of_clients: '180', number_of_households: '120', probability: '0', introduction_date: '2022-09-15', first_meeting_date: '2022-10-20', offer_made_date: '', hots_issued_date: '', hots_signed_date: '', deal_exchanged_date: '', deal_complete_date: '', latest_recurring_income: '£48,000', latest_new_business: '', latest_turnover: '£60,000', pipeline: 'Main Pipeline', label: '', broker_fee_value: '£5,940', receiving_office: '', vendor_ownership_structure: 'John Fahy', perspective_entity: 'Perspective Financial', perspective_principal: 'David McWilliams', perspective_regional_director: '', payment_schedule: '', deal_address: '', expected_close_date: '' },
  { id: '2', deal_pipedrive_id: '4488', title: 'Zest Financial Consultants Ltd', value: '£354,000', weighted_value: '£177,000', currency: 'GBP', stage: 'Declined', status: 'open', owner: 'David McWilliams', contact_id: '11', organisation_id: '2', date_created: '2022-11-05', introductory_company: 'Chapters Capital', deal_size: 'Medium (£300k-£600k EBITDA)', deal_source: 'M&A Broker', reason_for_decline: 'Valuation gap', reason_for_decline_detail: '', basis_of_deal: 'Share Purchase', fdd_lead: 'Alice Johnson', rdd_lead: 'Bob Smith', latest_status_acquisition_committee: 'Reviewed', acquisition_type: 'Full Acquisition', deal_structure: 'Cash', headline_consideration: '£354,000', ri_multiple: '3.8x', net_turnover_multiple: '1.8x', ebitda_multiple: '5.2x', assets_under_advice: '£110m', number_of_clients: '350', number_of_households: '250', probability: '0', introduction_date: '2022-07-10', first_meeting_date: '2022-08-15', offer_made_date: '', hots_issued_date: '', hots_signed_date: '', deal_exchanged_date: '', deal_complete_date: '', latest_recurring_income: '£68,000', latest_new_business: '', latest_turnover: '£95,000', pipeline: 'Main Pipeline', label: '', broker_fee_value: '£10,620', receiving_office: '', vendor_ownership_structure: 'Justin Riley', perspective_entity: 'Perspective Financial', perspective_principal: 'David McWilliams', perspective_regional_director: '', payment_schedule: '', deal_address: '', expected_close_date: '' },
  { id: '3', deal_pipedrive_id: '4489', title: 'Goodman Financial Planning', value: '£145,000', weighted_value: '£145,000', currency: 'GBP', stage: 'Completed', status: 'won', owner: 'David McWilliams', contact_id: '2', organisation_id: '2', date_created: '2019-01-10', introductory_company: '', deal_size: 'Small (<£300k EBITDA)', deal_source: 'Direct', latest_status_acquisition_committee: 'Complete', acquisition_type: 'Full Acquisition', deal_structure: 'Cash', headline_consideration: '£145,000', ri_multiple: '2.9x', net_turnover_multiple: '1.2x', ebitda_multiple: '3.8x', assets_under_advice: '£25m', number_of_clients: '95', number_of_households: '70', probability: '100', introduction_date: '2018-11-20', first_meeting_date: '2018-12-10', offer_made_date: '2019-03-15', hots_issued_date: '2019-04-01', hots_signed_date: '2019-05-10', deal_exchanged_date: '2019-07-16', deal_complete_date: '2019-07-16', basis_of_deal: 'Asset Purchase', fdd_lead: 'Alice Johnson', rdd_lead: 'Bob Smith', latest_recurring_income: '£38,000', latest_new_business: '', latest_turnover: '£50,000', pipeline: 'Main Pipeline', label: '', broker_fee_value: '£4,350', receiving_office: '', vendor_ownership_structure: 'Peter Goodman', perspective_entity: 'Perspective Financial', perspective_principal: 'David McWilliams', perspective_regional_director: '', reason_for_decline: '', reason_for_decline_detail: '', payment_schedule: '', deal_address: '', expected_close_date: '' },
  { id: '4', deal_pipedrive_id: '4490', title: 'Prolific Financial Services Limited (Project Providentia)', value: '£773,000', weighted_value: '£773,000', currency: 'GBP', stage: 'Completed', status: 'won', owner: 'David McWilliams', contact_id: '10', organisation_id: '10', date_created: '2020-09-15', introductory_company: 'Quantum Amalgamations', deal_size: 'Large (>£600k EBITDA)', deal_source: 'Intermediary', latest_status_acquisition_committee: 'Complete', acquisition_type: 'Full Acquisition', deal_structure: 'Cash + Deferred', headline_consideration: '£773,000', ri_multiple: '4.2x', net_turnover_multiple: '2.1x', ebitda_multiple: '6.5x', assets_under_advice: '£240m', number_of_clients: '720', number_of_households: '510', probability: '100', introduction_date: '2020-05-10', first_meeting_date: '2020-06-15', offer_made_date: '2020-10-20', hots_issued_date: '2020-12-01', hots_signed_date: '2021-01-15', deal_exchanged_date: '2021-06-25', deal_complete_date: '2021-06-25', basis_of_deal: 'Share Purchase', fdd_lead: 'Alice Johnson', rdd_lead: 'Carol White', latest_recurring_income: '£142,000', latest_new_business: '', latest_turnover: '£185,000', pipeline: 'Main Pipeline', label: '', broker_fee_value: '£23,190', receiving_office: '', vendor_ownership_structure: 'Simon Allan', perspective_entity: 'Perspective Financial', perspective_principal: 'David McWilliams', perspective_regional_director: '', reason_for_decline: '', reason_for_decline_detail: '', payment_schedule: '', deal_address: '', expected_close_date: '' },
  { id: '5', deal_pipedrive_id: '4491', title: 'Evolve Financial Management', value: '£122,000', weighted_value: '£122,000', currency: 'GBP', stage: 'Completed', status: 'won', owner: 'David McWilliams', contact_id: '5', organisation_id: '5', date_created: '2019-08-20', introductory_company: 'Boston Bailey - No Longer Active', deal_size: 'Small (<£300k EBITDA)', deal_source: 'M&A Broker', latest_status_acquisition_committee: 'Complete', acquisition_type: 'Full Acquisition', deal_structure: 'Cash', headline_consideration: '£122,000', ri_multiple: '2.8x', net_turnover_multiple: '1.1x', ebitda_multiple: '3.6x', assets_under_advice: '£190m', number_of_clients: '140', number_of_households: '95', probability: '100', deal_exchanged_date: '2020-09-11', deal_complete_date: '2021-03-12', introduction_date: '2019-06-05', first_meeting_date: '2019-07-12', offer_made_date: '2019-11-20', hots_issued_date: '2020-01-15', hots_signed_date: '2020-03-10', basis_of_deal: 'Asset Purchase', fdd_lead: 'Alice Johnson', rdd_lead: 'Bob Smith', latest_recurring_income: '£32,000', latest_new_business: '', latest_turnover: '£44,000', pipeline: 'Main Pipeline', label: '', broker_fee_value: '£3,660', receiving_office: '', vendor_ownership_structure: 'Mike Fisher', perspective_entity: 'Perspective Financial', perspective_principal: 'David McWilliams', perspective_regional_director: '', reason_for_decline: '', reason_for_decline_detail: '', payment_schedule: '', deal_address: '', expected_close_date: '' },
  { id: '6', deal_pipedrive_id: '4492', title: 'Avon Financial Advisers Ltd', value: '£158,000', weighted_value: '£158,000', currency: 'GBP', stage: 'Completed', status: 'won', owner: 'David McWilliams', contact_id: '7', organisation_id: '7', date_created: '2019-12-01', introductory_company: 'Retiring IFA', deal_size: 'Small (<£300k EBITDA)', deal_source: 'Direct', latest_status_acquisition_committee: 'Complete', acquisition_type: 'Full Acquisition', deal_structure: 'Cash', headline_consideration: '£158,000', ri_multiple: '3.1x', net_turnover_multiple: '1.3x', ebitda_multiple: '4.0x', assets_under_advice: '£370m', number_of_clients: '210', number_of_households: '150', probability: '100', deal_exchanged_date: '2021-06-24', deal_complete_date: '2021-07-30', introduction_date: '2019-10-15', first_meeting_date: '2019-11-20', offer_made_date: '2020-04-10', hots_issued_date: '2020-06-01', hots_signed_date: '2020-08-15', basis_of_deal: 'Asset Purchase', fdd_lead: 'Carol White', rdd_lead: 'Bob Smith', latest_recurring_income: '£38,500', latest_new_business: '', latest_turnover: '£55,000', pipeline: 'Main Pipeline', label: '', broker_fee_value: '£4,740', receiving_office: '', vendor_ownership_structure: 'Stephen Cook', perspective_entity: 'Perspective Financial', perspective_principal: 'David McWilliams', perspective_regional_director: '', reason_for_decline: '', reason_for_decline_detail: '', payment_schedule: '', deal_address: '', expected_close_date: '' },
  { id: '7', deal_pipedrive_id: '4493', title: 'Jones Hill Ltd', value: '£219,000', weighted_value: '£219,000', currency: 'GBP', stage: 'Completed', status: 'won', owner: 'David McWilliams', contact_id: '8', organisation_id: '8', date_created: '2019-11-15', introductory_company: 'Tomorrow IFA', deal_size: 'Small (<£300k EBITDA)', deal_source: 'Intermediary', latest_status_acquisition_committee: 'Complete', acquisition_type: 'Full Acquisition', deal_structure: 'Cash + Deferred', headline_consideration: '£219,000', ri_multiple: '3.4x', net_turnover_multiple: '1.6x', ebitda_multiple: '4.5x', assets_under_advice: '£440m', number_of_clients: '285', number_of_households: '190', probability: '100', deal_exchanged_date: '2020-07-10', deal_complete_date: '2020-09-03', introduction_date: '2019-09-01', first_meeting_date: '2019-10-15', offer_made_date: '2020-01-20', hots_issued_date: '2020-03-01', hots_signed_date: '2020-04-15', basis_of_deal: 'Share Purchase', fdd_lead: 'Alice Johnson', rdd_lead: 'Carol White', latest_recurring_income: '£52,000', latest_new_business: '', latest_turnover: '£70,000', pipeline: 'Main Pipeline', label: '', broker_fee_value: '£6,570', receiving_office: '', vendor_ownership_structure: 'Brian Hill', perspective_entity: 'Perspective Financial', perspective_principal: 'David McWilliams', perspective_regional_director: '', reason_for_decline: '', reason_for_decline_detail: '', payment_schedule: '', deal_address: '', expected_close_date: '' },
  { id: '8', deal_pipedrive_id: '4494', title: 'Atkinson White Ltd', value: '£734,000', weighted_value: '£734,000', currency: 'GBP', stage: 'Completed', status: 'won', owner: 'David McWilliams', contact_id: '4', organisation_id: '4', date_created: '2019-06-10', introductory_company: 'Gunner & Co', deal_size: 'Large (>£600k EBITDA)', deal_source: 'M&A Broker', latest_status_acquisition_committee: 'Complete', acquisition_type: 'Full Acquisition', deal_structure: 'Cash', headline_consideration: '£734,000', ri_multiple: '4.5x', net_turnover_multiple: '2.2x', ebitda_multiple: '7.1x', assets_under_advice: '£130m', number_of_clients: '480', number_of_households: '320', probability: '100', deal_exchanged_date: '2020-11-11', deal_complete_date: '2021-01-22', introduction_date: '2019-04-01', first_meeting_date: '2019-05-10', offer_made_date: '2019-09-20', hots_issued_date: '2019-11-01', hots_signed_date: '2019-12-15', basis_of_deal: 'Share Purchase', fdd_lead: 'Alice Johnson', rdd_lead: 'Bob Smith', latest_recurring_income: '£145,000', latest_new_business: '', latest_turnover: '£195,000', pipeline: 'Main Pipeline', label: '', broker_fee_value: '£22,020', receiving_office: '', vendor_ownership_structure: 'Neil White', perspective_entity: 'Perspective Financial', perspective_principal: 'David McWilliams', perspective_regional_director: '', reason_for_decline: '', reason_for_decline_detail: '', payment_schedule: '', deal_address: '', expected_close_date: '' },
  { id: '9', deal_pipedrive_id: '4495', title: 'Ian J Hunt & Associates', value: '£252,000', weighted_value: '£252,000', currency: 'GBP', stage: 'Completed', status: 'won', owner: 'David McWilliams', contact_id: '9', organisation_id: '9', date_created: '2021-09-20', introductory_company: 'Wealth Holdings', deal_size: 'Medium (£300k-£600k EBITDA)', deal_source: 'Intermediary', latest_status_acquisition_committee: 'Complete', acquisition_type: 'Full Acquisition', deal_structure: 'Cash', headline_consideration: '£252,000', ri_multiple: '3.6x', net_turnover_multiple: '1.7x', ebitda_multiple: '4.8x', assets_under_advice: '£370m', number_of_clients: '320', number_of_households: '220', probability: '100', deal_exchanged_date: '2022-03-08', deal_complete_date: '2023-01-13', introduction_date: '2021-07-15', first_meeting_date: '2021-08-20', offer_made_date: '2021-11-10', hots_issued_date: '2021-12-01', hots_signed_date: '2022-01-15', basis_of_deal: 'Asset Purchase', fdd_lead: 'Carol White', rdd_lead: 'Bob Smith', latest_recurring_income: '£58,000', latest_new_business: '', latest_turnover: '£78,000', pipeline: 'Main Pipeline', label: '', broker_fee_value: '£7,560', receiving_office: '', vendor_ownership_structure: 'Ian John Hunt', perspective_entity: 'Perspective Financial', perspective_principal: 'David McWilliams', perspective_regional_director: '', reason_for_decline: '', reason_for_decline_detail: '', payment_schedule: '', deal_address: '', expected_close_date: '' },
  { id: '10', deal_pipedrive_id: '4496', title: 'Strategic Financial Portfolios', value: '£189,000', weighted_value: '£94,500', currency: 'GBP', stage: 'HoTs Signed', status: 'open', owner: 'Sam Smith', contact_id: '3', organisation_id: '3', date_created: '2024-01-15', introductory_company: 'Churchill Mergers', deal_size: 'Small (<£300k EBITDA)', deal_source: 'M&A Broker', latest_status_acquisition_committee: 'In Progress', acquisition_type: 'Full Acquisition', deal_structure: 'Cash', headline_consideration: '£189,000', ri_multiple: '3.0x', net_turnover_multiple: '1.4x', ebitda_multiple: '3.9x', assets_under_advice: '£85m', number_of_clients: '230', number_of_households: '160', probability: '50', introduction_date: '2023-10-05', first_meeting_date: '2023-11-12', offer_made_date: '2024-02-20', hots_issued_date: '2024-04-01', hots_signed_date: '2024-05-15', deal_exchanged_date: '', deal_complete_date: '', basis_of_deal: 'Asset Purchase', fdd_lead: 'Alice Johnson', rdd_lead: 'Carol White', latest_recurring_income: '£45,000', latest_new_business: '', latest_turnover: '£62,000', pipeline: 'Main Pipeline', label: '', broker_fee_value: '£5,670', receiving_office: '', vendor_ownership_structure: 'Mohammed Bostan', perspective_entity: 'Perspective Financial', perspective_principal: 'Sam Smith', perspective_regional_director: '', reason_for_decline: '', reason_for_decline_detail: '', payment_schedule: '', deal_address: '', expected_close_date: '' },
  { id: '11', deal_pipedrive_id: '4497', title: 'Bowman Financial Planning Limited', value: '£267,000', weighted_value: '£133,500', currency: 'GBP', stage: 'Offer Made', status: 'open', owner: 'Sam Smith', contact_id: '6', organisation_id: '6', date_created: '2024-03-01', introductory_company: 'Gunner & Co', deal_size: 'Medium (£300k-£600k EBITDA)', deal_source: 'M&A Broker', latest_status_acquisition_committee: '', acquisition_type: 'Full Acquisition', deal_structure: 'Cash + Deferred', headline_consideration: '£267,000', ri_multiple: '3.3x', net_turnover_multiple: '1.5x', ebitda_multiple: '4.3x', assets_under_advice: '£92m', number_of_clients: '310', number_of_households: '210', probability: '40', introduction_date: '2024-01-10', first_meeting_date: '2024-02-08', offer_made_date: '2024-04-22', hots_issued_date: '', hots_signed_date: '', deal_exchanged_date: '', deal_complete_date: '', basis_of_deal: 'Asset Purchase', fdd_lead: '', rdd_lead: '', latest_recurring_income: '£58,000', latest_new_business: '', latest_turnover: '£75,000', pipeline: 'Main Pipeline', label: '', broker_fee_value: '£8,010', receiving_office: '', vendor_ownership_structure: 'Paul Catling', perspective_entity: 'Perspective Financial', perspective_principal: 'Sam Smith', perspective_regional_director: '', reason_for_decline: '', reason_for_decline_detail: '', payment_schedule: '', deal_address: '', expected_close_date: '' },
  { id: '12', deal_pipedrive_id: '4498', title: 'North London IFA Partnership', value: '£425,000', weighted_value: '£212,500', currency: 'GBP', stage: 'First Meeting Held', status: 'open', owner: 'Alice Johnson', contact_id: '12', organisation_id: '8', date_created: '2024-06-01', introductory_company: 'Berkeley Cannon', deal_size: 'Medium (£300k-£600k EBITDA)', deal_source: 'Intermediary', latest_status_acquisition_committee: '', acquisition_type: 'Full Acquisition', deal_structure: 'Cash', headline_consideration: '£425,000', ri_multiple: '3.7x', net_turnover_multiple: '1.9x', ebitda_multiple: '5.5x', assets_under_advice: '£155m', number_of_clients: '410', number_of_households: '280', probability: '30', introduction_date: '2024-04-15', first_meeting_date: '2024-05-20', offer_made_date: '', hots_issued_date: '', hots_signed_date: '', deal_exchanged_date: '', deal_complete_date: '', basis_of_deal: 'Share Purchase', fdd_lead: '', rdd_lead: '', latest_recurring_income: '£78,000', latest_new_business: '', latest_turnover: '£105,000', pipeline: 'Main Pipeline', label: '', broker_fee_value: '£12,750', receiving_office: '', vendor_ownership_structure: 'Joe Hill', perspective_entity: 'Perspective Financial', perspective_principal: 'Alice Johnson', perspective_regional_director: '', reason_for_decline: '', reason_for_decline_detail: '', payment_schedule: '', deal_address: '', expected_close_date: '' },
]

export const users = [
  { id: '1', name: 'Aamna Hussain', email: 'aamna.hussain@pfgl.co.uk', user_status: 'active', user_roles: 'Staff', organisation_id: '1', pipedrive_id: '', user_permissions: ['view', 'edit'], date_created: '2021-03-01' },
  { id: '2', name: 'Aisha Fayyaz', email: 'aisha.fayyaz@pfgl.co.uk', user_status: 'active', user_roles: 'Staff', organisation_id: '1', pipedrive_id: '', user_permissions: ['view', 'edit'], date_created: '2021-04-15' },
  { id: '3', name: 'David McWilliams', email: 'david.mcwilliams@pfgl.co.uk', user_status: 'active', user_roles: 'Admin', organisation_id: '1', pipedrive_id: 'PD001', user_permissions: ['view', 'edit', 'delete', 'admin'], date_created: '2018-01-10' },
  { id: '4', name: 'Sam Smith', email: 'sam.smith@pfgl.co.uk', user_status: 'active', user_roles: 'Sales', organisation_id: '1', pipedrive_id: 'PD002', user_permissions: ['view', 'edit'], date_created: '2019-06-20' },
  { id: '5', name: 'Alice Johnson', email: 'alice.johnson@pfgl.co.uk', user_status: 'active', user_roles: 'Sales', organisation_id: '1', pipedrive_id: 'PD003', user_permissions: ['view', 'edit'], date_created: '2020-02-14' },
  { id: '6', name: 'Bob Smith', email: 'bob.smith@pfgl.co.uk', user_status: 'active', user_roles: 'Dev', organisation_id: '1', pipedrive_id: '', user_permissions: ['view', 'edit', 'admin'], date_created: '2020-09-01' },
  { id: '7', name: 'Carol White', email: 'carol.white@pfgl.co.uk', user_status: 'active', user_roles: 'Staff', organisation_id: '1', pipedrive_id: '', user_permissions: ['view'], date_created: '2021-11-30' },
  { id: '8', name: 'James Taylor', email: 'james.taylor@pfgl.co.uk', user_status: 'inactive', user_roles: 'Staff', organisation_id: '1', pipedrive_id: '', user_permissions: ['view'], date_created: '2022-03-22' },
  { id: '9', name: 'Sarah Connor', email: 'sarah.connor@pfgl.co.uk', user_status: 'active', user_roles: 'Staff', organisation_id: '1', pipedrive_id: '', user_permissions: ['view', 'edit'], date_created: '2023-01-15' },
  { id: '10', name: 'Michael Brown', email: 'michael.brown@pfgl.co.uk', user_status: 'active', user_roles: 'Admin', organisation_id: '1', pipedrive_id: 'PD004', user_permissions: ['view', 'edit', 'delete', 'admin'], date_created: '2018-05-05' },
]
